"""create meeting rooms table

Revision ID: 30c867fb1499
Revises: 6b3cd9b0415a
Create Date: 2026-09-16 09:40:12.014712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c867fb1499'
down_revision: Union[str, Sequence[str], None] = '6b3cd9b0415a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('room_code', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('facilities', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_meeting_rooms_id'), 'meeting_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_rooms_room_code'), 'meeting_rooms', ['room_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_rooms_room_code'), table_name='meeting_rooms')
    op.drop_index(op.f('ix_meeting_rooms_id'), table_name='meeting_rooms')
    op.drop_table('meeting_rooms')
    # ### end Alembic commands ###
