"""create booking resources table

Revision ID: b7fa2ad6e950
Revises: 53a7dccc9198
Create Date: 2026-09-16 11:11:59.202101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fa2ad6e950'
down_revision: Union[str, Sequence[str], None] = '53a7dccc9198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_resources_booking_id'), 'booking_resources', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_resources_id'), 'booking_resources', ['id'], unique=False)
    op.create_index(op.f('ix_booking_resources_resource_id'), 'booking_resources', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_resources_resource_id'), table_name='booking_resources')
    op.drop_index(op.f('ix_booking_resources_id'), table_name='booking_resources')
    op.drop_index(op.f('ix_booking_resources_booking_id'), table_name='booking_resources')
    op.drop_table('booking_resources')
    # ### end Alembic commands ###
